name: My action 

on:
  workflow_dispatch:
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
    
jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Call Hello World 
        id: hello-world
        uses: actions/hello-world-action@v1
      - name: Comment
        run: echo 'Output - ${{ steps.hello-world.outputs.random-number }}'
