name: My action 

on:
  workflow_dispatch:
    
jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Call Hello World 
        id: hello-world
        uses: ./.github/workflows/hello-world-action
      - name: Comment
        run: echo 'Output - ${{ steps.hello-world.outputs.random-number }}'
      - name: Composite Check
        uses: ./.github/workflows/read-output
        with: 
          rand: ${{ steps.hello-world.outputs.random-number }}
